name: complex
method: POST
language: typescript
entrypoint: complex.ts
entrypoint_function: processUsers

payload:
  - users: list
  - requireActive: boolean

return_type: ProcessSummary
port: 3001
endpoint: /complex
