name: net
language: typescript
entrypoint: net.ts
entrypoint_function: net
port: 3005
endpoint: /net
method: POST
payload:
  - msg: string
  - request_catcher: string
return_type: string
capabilities:
  stdio: true
  network:
    http: true
    tcp: true
    dns: true
