name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: Cache Cargo registry and build artifacts
      uses: Swatinem/rust-cache@v2

    - name: Check Formatting
      run: cargo fmt --all -- --check
      continue-on-error: true

    - name: Clippy Lints
      run: cargo clippy --workspace

    - name: Build
      run: cargo build --workspace --verbose

    - name: Run Tests
      run: cargo test --workspace --verbose
